// Nuvem Fofa v0.3.14 FINAL
(() => {
  const $=id=>document.getElementById(id), qa=(s,r=document)=>[...r.querySelectorAll(s)];
  const imagePending={avatar:null,banner:null,serverIcon:null,serverCover:null};
  const css=document.createElement('style');css.textContent=`
  #sharePickerModal .nf-discord-picker-head,#sharePickerModal .nf-discord-bottom,#sharePickerModal .nf-stream-modebar,#sharePickerModal .nf-stream-pop,#sharePickerModal .nf-device-tab{display:none!important}
  #sharePickerModal{background:#000b!important;backdrop-filter:blur(4px)}
  #sharePickerModal .share-picker-card{position:relative!important;width:min(820px,92vw)!important;max-height:86vh!important;overflow:hidden!important;background:#191a1d!important;border:1px solid #303238!important;border-radius:14px!important;box-shadow:0 24px 80px #000c!important;display:flex!important;flex-direction:column!important}
  #sharePickerModal .modal-head{display:none!important}
  #sharePickerModal .share-tabs{display:grid!important;grid-template-columns:repeat(3,1fr)!important;gap:4px!important;padding:5px!important;margin:0!important;background:#101114!important;border-bottom:1px solid #292b30!important;flex:0 0 auto!important}
  #sharePickerModal .share-tabs button{height:43px!important;border:0!important;border-radius:9px!important;background:transparent!important;color:#aeb3bb!important;font-weight:700!important;display:flex!important;align-items:center!important;justify-content:center!important;gap:8px!important;cursor:pointer!important}
  #sharePickerModal .share-tabs button:hover{background:#202226!important;color:#fff!important}#sharePickerModal .share-tabs button.active{background:#2b2d31!important;color:#fff!important}
  #sharePickerModal .share-tabs svg{width:17px;height:17px;fill:none;stroke:currentColor;stroke-width:1.8}
  #sharePickerModal .share-sources{flex:1 1 auto!important;min-height:250px!important;max-height:390px!important;overflow:auto!important;display:grid!important;grid-template-columns:repeat(2,minmax(0,1fr))!important;align-content:start!important;gap:12px!important;padding:16px!important;background:#191a1d!important}
  #sharePickerModal .share-source{min-width:0!important;border:2px solid transparent!important;border-radius:10px!important;background:#232428!important;padding:7px!important;color:#f2f3f5!important;text-align:left!important;cursor:pointer!important}
  #sharePickerModal .share-source:hover{background:#2b2d31!important;border-color:#44474f!important}#sharePickerModal .share-source.active{border-color:#5865f2!important;background:#2b2d31!important}
  #sharePickerModal .share-source img{display:block!important;width:100%!important;aspect-ratio:16/9!important;object-fit:cover!important;margin:0 0 7px!important;border-radius:7px!important;background:#0d0e10!important;filter:none!important}
  #sharePickerModal .share-source-name{font-size:13px!important;font-weight:700!important;white-space:nowrap!important;overflow:hidden!important;text-overflow:ellipsis!important}
  #sharePickerModal .share-options{display:grid!important;grid-template-columns:1fr 1fr!important;gap:14px 22px!important;padding:13px 16px 7px!important;background:#191a1d!important;border-top:1px solid #292b30!important;flex:0 0 auto!important}
  #sharePickerModal .share-options>div label{display:block!important;margin:0 0 7px!important;color:#949ba4!important;font-size:11px!important;font-weight:800!important;text-transform:uppercase!important}
  #sharePickerModal .share-choice-row{display:flex!important;gap:7px!important}#sharePickerModal .share-choice-row button{height:37px!important;min-width:68px!important;padding:0 12px!important;border:1px solid #3f4147!important;border-radius:7px!important;background:#232428!important;color:#dbdee1!important;cursor:pointer!important}
  #sharePickerModal .share-choice-row button.active{background:#5865f2!important;border-color:#5865f2!important;color:#fff!important}
  #sharePickerModal .share-audio-toggle{grid-column:1/-1!important;display:flex!important;align-items:center!important;gap:9px!important;padding-bottom:4px!important;color:#dbdee1!important;font-size:13px!important;font-weight:600!important}#sharePickerModal .share-audio-toggle input{width:17px;height:17px;accent-color:#5865f2}
  #sharePickerModal .modal-actions{display:flex!important;justify-content:flex-end!important;gap:8px!important;padding:8px 16px 13px!important;background:#191a1d!important;border:0!important;flex:0 0 auto!important}#sharePickerModal .modal-actions button{height:39px!important;border-radius:7px!important;padding:0 15px!important}
  #sharePickerModal .nf314-footer{display:flex!important;align-items:center!important;gap:12px!important;padding:10px 13px!important;background:#101114!important;border-top:1px solid #292b30!important;flex:0 0 auto!important}
  #sharePickerModal .nf314-footer-copy{min-width:0;flex:1}.nf314-footer-copy b{display:block;color:#f2f3f5;font-size:13px}.nf314-footer-copy small{display:block;color:#949ba4;font-size:11px;margin-top:2px}
  #sharePickerModal .nf314-footer-gear{width:38px;height:38px;border:0;border-radius:8px;background:#232428;color:#dbdee1;display:grid;place-items:center;cursor:pointer}#sharePickerModal .nf314-footer-gear:hover{background:#35373c;color:#fff}
  #sharePickerModal .nf314-menu{position:absolute;right:13px;bottom:57px;width:275px;padding:7px;background:#111214;border:1px solid #303238;border-radius:10px;box-shadow:0 18px 55px #000d;z-index:40}.nf314-menu-title{padding:6px 8px;color:#949ba4;font-size:11px;font-weight:800;text-transform:uppercase}.nf314-menu button{width:100%;display:flex;align-items:center;gap:9px;border:0;border-radius:6px;background:transparent;color:#dbdee1;text-align:left;padding:9px 10px;cursor:pointer}.nf314-menu button:hover{background:#35373c}.nf314-menu button.active{color:#fff}.nf314-radio{margin-left:auto;width:16px;height:16px;border:2px solid #72767d;border-radius:50%;display:grid;place-items:center}.nf314-menu button.active .nf314-radio:after{content:'';width:8px;height:8px;border-radius:50%;background:#5865f2}
  #sharePickerModal .nf314-device-empty{grid-column:1/-1;min-height:230px;display:grid;place-items:center;text-align:center;color:#949ba4}.nf314-device-empty b{display:block;color:#dbdee1;margin-bottom:5px}
  #profileAvatarPreview,#meAvatar,#viewUserAvatar,.avatar,.msg-avatar,.voice-avatar-xl,#serverIconPreview,#serverCoverPreview,#profileBanner,#viewUserBanner{filter:none!important;-webkit-filter:none!important;mix-blend-mode:normal!important;opacity:1!important}
  @media(max-width:720px){#sharePickerModal .share-sources{grid-template-columns:1fr!important}#sharePickerModal .share-options{grid-template-columns:1fr!important}.share-audio-toggle{grid-column:1!important}}
  `;document.head.appendChild(css);

  const icon={app:'<svg viewBox="0 0 24 24"><rect x="3" y="4" width="18" height="16" rx="2"/><path d="M3 8h18"/></svg>',screen:'<svg viewBox="0 0 24 24"><rect x="3" y="4" width="18" height="13" rx="2"/><path d="M8 21h8M12 17v4"/></svg>',device:'<svg viewBox="0 0 24 24"><path d="M4 6h12a2 2 0 0 1 2 2v8a2 2 0 0 1-2 2H4a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2Z"/><path d="m18 10 4-2v8l-4-2"/></svg>',gear:'<svg viewBox="0 0 24 24" width="19" height="19" fill="currentColor"><path d="M12 8.5a3.5 3.5 0 1 0 0 7 3.5 3.5 0 0 0 0-7Zm8.7 2.1-1.6-.5a8 8 0 0 0-.7-1.6l.8-1.5-2.2-2.2-1.5.8a8 8 0 0 0-1.6-.7L13.4 3h-2.8l-.5 1.9a8 8 0 0 0-1.6.7L7 4.8 4.8 7l.8 1.5a8 8 0 0 0-.7 1.6l-1.9.5v2.8l1.9.5c.2.6.4 1.1.7 1.6L4.8 17 7 19.2l1.5-.8c.5.3 1 .5 1.6.7l.5 1.9h2.8l.5-1.9c.6-.2 1.1-.4 1.6-.7l1.5.8 2.2-2.2-.8-1.5c.3-.5.5-1 .7-1.6l1.6-.5v-2.8Z"/></svg>'};

  function cropData(){if(!cropState?.img)return null;const type=cropState.type,square=type==='avatar'||type==='serverIcon',ow=square?512:1200,oh=square?512:400,img=cropState.img,f=cropFrame(),z=Math.max(1,+cropState.z||1),x=+cropState.x||0,y=+cropState.y||0,base=Math.max(f.w/img.width,f.h/img.height)*z,sw=Math.min(img.width,f.w/base),sh=Math.min(img.height,f.h/base),sx=Math.max(0,Math.min(img.width-sw,(img.width-sw)/2-x/base)),sy=Math.max(0,Math.min(img.height-sh,(img.height-sh)/2-y/base)),c=document.createElement('canvas');c.width=ow;c.height=oh;const ctx=c.getContext('2d',{alpha:true});ctx.imageSmoothingEnabled=true;ctx.imageSmoothingQuality='high';ctx.clearRect(0,0,ow,oh);ctx.drawImage(img,sx,sy,sw,sh,0,0,ow,oh);return c.toDataURL('image/webp',.88)}
  function applyFinalCrop(){if(!cropState)return;const type=cropState.type,data=cropData();if(!data)return toast('Não consegui processar a imagem.');if(type==='avatar'){imagePending.avatar=data;pendingAvatarData=data;$('profileAvatarPreview').src=data}else if(type==='banner'){imagePending.banner=data;pendingBannerData=data;$('profileBanner').style.backgroundImage=`url("${data}")`}else if(type==='serverIcon'){imagePending.serverIcon=data;window.pendingServerIcon=data;const p=$('serverIconPreview');p.style.backgroundImage=`url("${data}")`;p.textContent=''}else if(type==='serverBanner'){imagePending.serverCover=data;pendingServerCover=data;$('serverCoverPreview').style.backgroundImage=`url("${data}")`}try{cropState.input.value=''}catch{}cropState=null;closeModal('cropModal')}
  window.applyCrop=applyFinalCrop;
  function bindCropButton(){const b=qa('#cropModal .modal-actions button').find(x=>/aplicar/i.test(x.textContent||''));if(b&&b.dataset.nf314!=='1'){b.dataset.nf314='1';b.removeAttribute('onclick');b.onclick=e=>{e.preventDefault();e.stopPropagation();applyFinalCrop()}}}
  bindCropButton();

  const baseOpenProfile=window.openProfile||openProfile;window.openProfile=function(){baseOpenProfile();imagePending.avatar=null;imagePending.banner=null;setTimeout(bindCropButton,0)};
  window.saveProfile=async function(){if(!currentUser||!db)return;const uid=currentUser.uid,av=imagePending.avatar||pendingAvatarData||null,bn=imagePending.banner||pendingBannerData||null;try{await db.ref(`users/${uid}`).update({username:$('profileUsername')?.value?.trim()||currentUserData?.username||'Usuário',status:$('profileStatus')?.value?.trim()||'',bio:$('profileBio')?.value?.trim()||'',updatedAt:firebase.database.ServerValue.TIMESTAMP});if(av)await db.ref(`users/${uid}/avatar`).set(av);if(bn)await db.ref(`users/${uid}/banner`).set(bn);const s=await db.ref(`users/${uid}`).once('value'),d=s.val()||{};if(av&&d.avatar!==av)throw new Error('a foto de perfil não foi confirmada');if(bn&&d.banner!==bn)throw new Error('a capa do perfil não foi confirmada');currentUserData=d;imagePending.avatar=imagePending.banner=null;pendingAvatarData=pendingBannerData=null;$('meAvatar').src=imgFor(d);$('profileAvatarPreview').src=imgFor(d);$('profileBanner').style.backgroundImage=d.banner?`url("${d.banner}")`:'';if(voiceRoom)await db.ref(`voiceParticipants/${voiceRoom.channelId}/${uid}`).update({avatar:d.avatar||'',username:d.username||'Usuário'}).catch(()=>{});qa(`[data-voice-user="${uid}"] img`).forEach(i=>i.src=imgFor(d));if(voiceRoom){renderVoicePanel();refreshVoiceCallGrid();refreshVoiceSidebarParticipants()}closeModal('profileModal');toast('Perfil atualizado com a nova imagem.')}catch(e){console.error('[v0.3.14 profile]',e);toast('Erro real ao salvar imagem: '+(e.message||'desconhecido'))}};

  const baseOpenServer=window.openServerSettings||openServerSettings;window.openServerSettings=async function(){await baseOpenServer();imagePending.serverIcon=imagePending.serverCover=null;const s=await db.ref(`servers/${currentServer}`).once('value'),d=s.val()||{},p=$('serverIconPreview');if(p){p.style.backgroundImage=d.icon?`url("${d.icon}")`:'';p.textContent=d.icon?'':(d.name||'S').slice(0,1).toUpperCase()}$('serverCoverPreview').style.backgroundImage=d.cover?`url("${d.cover}")`:'';setTimeout(bindCropButton,0)};
  window.saveServerSettings=async function(){if(!currentServer||!db)return;const sid=currentServer,ic=imagePending.serverIcon||window.pendingServerIcon||null,cv=imagePending.serverCover||pendingServerCover||null;try{await db.ref(`servers/${sid}/name`).set($('serverEditName')?.value?.trim()||'Servidor');if(ic)await db.ref(`servers/${sid}/icon`).set(ic);if(cv)await db.ref(`servers/${sid}/cover`).set(cv);const s=await db.ref(`servers/${sid}`).once('value'),d=s.val()||{};if(ic&&d.icon!==ic)throw new Error('a foto do servidor não foi confirmada');if(cv&&d.cover!==cv)throw new Error('a capa do servidor não foi confirmada');imagePending.serverIcon=imagePending.serverCover=null;window.pendingServerIcon=null;pendingServerCover=null;closeModal('serverSettingsModal');loadServers();selectServer(sid,d);toast('Servidor atualizado com as novas imagens.')}catch(e){console.error('[v0.3.14 server]',e);toast('Erro real ao salvar imagem do servidor: '+(e.message||'desconhecido'))}};

  function modeText(){const s=sharePickerState||{},m=window.__nf314Mode||'games';if(m==='text')return['Compartilhamento de tela','Texto mais claro'];if(m==='custom')return['Personalizada','Configuração escolhida'];return['Jogos',`Vídeo mais suave · ${s.quality||1080}p · ${s.fps||60}fps`]}
  function updateFooter(){const f=$('sharePickerModal')?.querySelector('.nf314-footer-copy');if(!f)return;const [a,b]=modeText();f.innerHTML=`<b>${a}</b><small>${b}</small>`}
  function toggleMenu(card){let m=card.querySelector('.nf314-menu');if(m){m.remove();return}m=document.createElement('div');m.className='nf314-menu';m.innerHTML=`<div class="nf314-menu-title">Modo de transmissão</div><button class="${(window.__nf314Mode||'games')==='games'?'active':''}" data-mode="games"><span><b>Jogos</b><br><small>Vídeo mais suave</small></span><span class="nf314-radio"></span></button><button class="${window.__nf314Mode==='text'?'active':''}" data-mode="text"><span><b>Compartilhamento de tela</b><br><small>Texto mais claro</small></span><span class="nf314-radio"></span></button><button class="${window.__nf314Mode==='custom'?'active':''}" data-mode="custom"><span><b>Personalizada</b></span><span class="nf314-radio"></span></button><div class="nf314-menu-title">Áudio</div><button data-audio><span>Compartilhar áudio do sistema</span><span>${$('shareAudioToggle')?.checked===false?'':'✓'}</span></button>`;card.appendChild(m);qa('button[data-mode]',m).forEach(b=>b.onclick=()=>{window.__nf314Mode=b.dataset.mode;updateFooter();m.remove()});m.querySelector('[data-audio]').onclick=()=>{const c=$('shareAudioToggle');if(c)c.checked=!c.checked;m.remove()}}
  function renderDeviceTab(){sharePickerState.tab='device';sharePickerState.sourceId=null;$('shareTabApps')?.classList.remove('active');$('shareTabScreens')?.classList.remove('active');$('shareTabDevices')?.classList.add('active');$('shareSources').innerHTML='<div class="nf314-device-empty"><div><b>Dispositivos de vídeo</b><span>Nenhuma fonte de tela é mostrada nesta guia.</span></div></div>';$('shareStartBtn').disabled=true}
  function ensurePanel(){const m=$('sharePickerModal'),card=m?.querySelector('.share-picker-card'),tabs=card?.querySelector('.share-tabs');if(!card||!tabs)return;$('shareTabApps').innerHTML=icon.app+'<span>Aplicativos</span>';$('shareTabScreens').innerHTML=icon.screen+'<span>Tela Inteira</span>';let d=$('shareTabDevices');if(!d){d=document.createElement('button');d.id='shareTabDevices';d.innerHTML=icon.device+'<span>Dispositivos</span>';d.onclick=renderDeviceTab;tabs.appendChild(d)}if(!card.querySelector('.nf314-footer')){const f=document.createElement('div');f.className='nf314-footer';f.innerHTML=`<div class="nf314-footer-copy"></div><button class="nf314-footer-gear" title="Configurações da transmissão">${icon.gear}</button>`;card.appendChild(f);f.querySelector('.nf314-footer-gear').onclick=e=>{e.stopPropagation();toggleMenu(card)}}updateFooter()}
  const baseTab=window.setShareTab||setShareTab;window.setShareTab=function(tab){if(tab==='device')return renderDeviceTab();$('shareTabDevices')?.classList.remove('active');const r=baseTab(tab);setTimeout(ensurePanel,0);return r};
  const baseQ=window.chooseShareQuality||chooseShareQuality;window.chooseShareQuality=function(v,b){const r=baseQ(v,b);updateFooter();return r};const baseF=window.chooseShareFps||chooseShareFps;window.chooseShareFps=function(v,b){const r=baseF(v,b);updateFooter();return r};
  const baseOpenShare=window.openSharePicker||openSharePicker;window.openSharePicker=async function(){const r=await baseOpenShare();setTimeout(ensurePanel,20);return r};
  document.addEventListener('click',e=>{if(!e.target.closest('.nf314-menu')&&!e.target.closest('.nf314-footer-gear'))qa('#sharePickerModal .nf314-menu').forEach(x=>x.remove())},true);
  const observer=new MutationObserver(()=>{bindCropButton();if($('sharePickerModal')?.classList.contains('active'))ensurePanel()});observer.observe(document.documentElement,{childList:true,subtree:true,attributes:true,attributeFilter:['class']});
  ensurePanel();console.info('[Nuvem Fofa] v0.3.14 FINAL carregado');
})();
