// Nuvem Fofa v4.0.0 — camada de estabilização de voz, transmissão e layout
(()=>{'use strict';
const $=id=>document.getElementById(id),qa=(s,r=document)=>[...r.querySelectorAll(s)],clamp=(n,a,b)=>Math.max(a,Math.min(b,n));
window.NF4={version:'4.0.0',streamAudio:localStorage.getItem('nf4StreamAudio')!=='0',userGain:new Map()};
const css=document.createElement('style');css.textContent=`body.nf4 #voiceCallGrid{display:grid!important;grid-template-columns:repeat(2,minmax(0,1fr))!important;grid-auto-rows:minmax(220px,1fr)!important;gap:8px!important;align-content:stretch!important}body.nf4 #voiceCallGrid .voice-tile{width:100%!important;height:100%!important;min-height:220px!important;aspect-ratio:16/9!important;max-height:none!important;border-radius:8px!important;overflow:hidden!important}body.nf4 #voiceCallGrid video{width:100%!important;height:100%!important;object-fit:contain!important;background:#000!important}@media(max-width:850px){body.nf4 #voiceCallGrid{grid-template-columns:1fr!important}}`;document.head.appendChild(css);document.body.classList.add('nf4');
function audioEls(uid){return qa(`audio[id="voiceAudio-${uid}"],audio[id="voiceScreenAudio-${uid}"]`)}
function volume(uid){return clamp(Number(localStorage.getItem('nfUserVolume:'+uid)??1),0,2)}
function connectGain(a,v){try{let x=NF4.userGain.get(a);if(!x){const C=window.AudioContext||window.webkitAudioContext,ctx=window.__nf4AudioCtx||(window.__nf4AudioCtx=new C()),src=ctx.createMediaElementSource(a),gain=ctx.createGain();src.connect(gain);gain.connect(ctx.destination);x={ctx,gain};NF4.userGain.set(a,x)}x.gain.gain.setTargetAtTime(v,x.ctx.currentTime,.015);x.ctx.resume?.().catch(()=>{})}catch(e){console.warn('[NF4] gain',e)}}
function applyVolume(uid){const v=volume(uid),muted=localStorage.getItem('nfUserMuted:'+uid)==='1';audioEls(uid).forEach(a=>{a.muted=muted||!!window.voiceDeafened;if(v>1){a.volume=1;connectGain(a,v)}else{a.volume=v;const x=NF4.userGain.get(a);if(x)x.gain.gain.setTargetAtTime(1,x.ctx.currentTime,.015)}})}
function healAudio(){qa('audio[id^="voiceAudio-"],audio[id^="voiceScreenAudio-"]').forEach(a=>{const uid=a.id.replace(/^voice(?:Screen)?Audio-/,'');applyVolume(uid);if(a.srcObject&&a.paused)a.play().catch(()=>{})});window.__nf4AudioCtx?.resume?.().catch(()=>{})}
['pointerdown','keydown','click'].forEach(ev=>document.addEventListener(ev,healAudio,{capture:true,passive:true}));document.addEventListener('visibilitychange',()=>{if(!document.hidden)setTimeout(healAudio,50)});window.addEventListener('focus',()=>setTimeout(healAudio,50));setInterval(healAudio,1500);
window.nf4SetStreamAudio=function(on){NF4.streamAudio=!!on;localStorage.setItem('nf4StreamAudio',on?'1':'0');try{localScreenStream?.getAudioTracks?.().forEach(t=>t.enabled=!!on)}catch{};syncShareAudioUI();return NF4.streamAudio};
function syncShareAudioUI(){qa('#shareAudioToggle,[data-share-audio],.nf-share-audio').forEach(el=>{if('checked'in el&&el.checked!==NF4.streamAudio)el.checked=NF4.streamAudio;el.classList.toggle('on',NF4.streamAudio);el.setAttribute('aria-checked',String(NF4.streamAudio))})}
document.addEventListener('change',e=>{if(e.target?.matches?.('#shareAudioToggle,[data-share-audio],.nf-share-audio'))nf4SetStreamAudio(!!e.target.checked)},true);setTimeout(syncShareAudioUI,0);
function safeTrack(uid,e){const track=e.track;if(track?.kind!=='audio')return;const stream=new MediaStream([track]),hasVideo=(e.streams||[]).some(s=>s.getVideoTracks().length),id=(hasVideo?'voiceScreenAudio-':'voiceAudio-')+uid;let a=$(id);if(!a){a=document.createElement('audio');a.id=id;a.autoplay=true;a.playsInline=true;a.style.display='none';document.body.appendChild(a)}a.srcObject=stream;applyVolume(uid);a.play().catch(()=>{})}
const oldCreate=window.createPeer;if(typeof oldCreate==='function')window.createPeer=async function(uid){const pc=await oldCreate.apply(this,arguments);if(pc&&!pc.__nf4){pc.__nf4=true;const prev=pc.ontrack;pc.ontrack=e=>{try{prev?.call(pc,e)}finally{safeTrack(uid,e);setTimeout(()=>applyVolume(uid),0)}}}return pc};
const oldStart=window.startSelectedShare;if(typeof oldStart==='function')window.startSelectedShare=async function(){const wanted=$('shareAudioToggle')?.checked!==false;nf4SetStreamAudio(wanted);const r=await oldStart.apply(this,arguments);try{if(!wanted&&localScreenStream){const ats=localScreenStream.getAudioTracks();for(const tr of ats){for(const pc of Object.values(voicePeers||{})){for(const sender of pc.getSenders())if(sender.track?.id===tr.id)try{pc.removeTrack(sender)}catch{}}tr.stop();localScreenStream.removeTrack(tr)}}else if(wanted)localScreenStream?.getAudioTracks?.().forEach(t=>t.enabled=true)}catch(e){console.warn('[NF4] stream audio policy',e)}return r};
window.setStreamVolume=function(uid,val){const v=clamp(Number(val),0,2);localStorage.setItem('nfUserVolume:'+uid,String(v));applyVolume(uid);const label=$('streamVolLabel-'+uid);if(label)label.textContent=Math.round(v*100)+'%'};
window.streamVolumeMarkup=function(uid){const v=volume(uid);return `<div class="stream-volume"><input type="range" min="0" max="2" step="0.01" value="${v}" oninput="setStreamVolume('${uid}',this.value)"><span id="streamVolLabel-${uid}">${Math.round(v*100)}%</span></div>`};
console.info('[Nuvem Fofa] v4.0.0 core carregado');
})();
